version: '2'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.2
    ports:
      - "12201:12201/udp"
      - "5044:5044"
    environment:
      - "xpack.monitoring.elasticsearch.url=http://elasticsearch:9200"
    volumes:
      - ./resources/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf --config.reload.automatic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_SECURITY_ENABLED: "false"
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "ES_JAVA_OPTS=-Xmx2g -Xms2g"
      - "xpack.security.enabled=false"

volumes:
  elasticsearch_data:
