datadir: /data
zappsdir: ./example
wallet:
  keystore_path: /data/keystore
mode: zappdev
log:
  sendLogs: false
  level: debug
storage:
  arweave_host: arlocal
  arweave_protocol: http
  arweave_port: 1984
  use_arweave_bundler: false
  use_arlocal: true
  arweave_gateway_url: http://arlocal:1984/graphql
network:
  default_network: "local"
  web3:
    local:
      http_address: "blockchain_node:7545"
      ws_address: "blockchain_node:7545"
      gas_price_wei: 1000000
api:
  address: 0.0.0.0
zproxy:
  host: 0.0.0.0
