name: Point-Network-Node-Docker-Image-Builder-And-Publisher
on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }}

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: pointnetwork/pointnetwork_node
    steps:
      - uses: actions/checkout@v1
      - name: Get the Source Tag
        id: get_source_tag
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Log into the Docker Hub
        run: docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      - name: Build the Image
        run: docker build -t "${{ env.IMAGE_NAME }}:${{ steps.get_source_tag.outputs.SOURCE_TAG }}" .
      - name: Publish the Image
        run: docker push "${{ env.IMAGE_NAME }}:${{ steps.get_source_tag.outputs.SOURCE_TAG }}"
