name: ðŸ“‹ Compile release change log

on:
  pull_request:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-20.04
    if: ${{ startsWith(github.head_ref, 'release/') }}
    steps:
      - name: ðŸ· Get latest release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft

      - name: ðŸ· Get current version
        id: get_current_version
        run: echo release=$(echo $GITHUB_HEAD_REF | awk '{gsub("release/",""); print}') >> $GITHUB_OUTPUT

      - name: ðŸ“‹ Generate release change log
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sinceTag: ${{ steps.get_latest_release.outputs.release }}
          futureRelease: ${{ steps.get_current_version.outputs.release }}
          releaseBranch:  ${{ github.head_ref }}
