# Thiw workflow publishes the latest draft release
name: Publish Release

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Latest Draft Releas
    runs-on: ubuntu-latest
    steps:
    - uses: ivangabriele/publish-latest-release@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
